config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/users/:id/watch_list', to: 'users_contents#index',
                               as: 'users_watch_list'

  get '/users/:id/change_role', to: 'users#change_role',
                                as: 'user_change_role'

  devise_for :users, skip: [:registrations]

  resources :users
  resources :contents

  get 'contents/:id/add_favorite', to: 'users_contents#add_favorite',
                                   as: 'add_favorite'
  get 'contents/:id/remove_favorite', to: 'users_contents#remove_favorite',
                                      as: 'remove_favorite'
  get 'contents/:id/add_rating', to: 'users_contents#add_rating',
                                 as: 'add_rating'
  get 'contents/:id/add_watch_list', to: 'users_contents#add_watch_list',
                                     as: 'add_watch_list'
  get 'contents/:id/remove_watch_list', to: 'users_contents#remove_watch_list',
                                        as: 'remove_watch_list'
end

app/models/content.rb
class Content < ApplicationRecord
  has_many :user_content, dependent: :destroy
  has_many :users, through: :user_content, dependent: :destroy

  validates :title, presence: true
  validates :director, presence: true
  validates :year, presence: true
  validates :category, presence: true
  validates :file_path, presence: true

  def self.search(title, director, first_year, second_year, category)
    if first_year.blank?
      where("upper(title) LIKE upper(?) AND
             upper(director) LIKE upper(?) AND
             upper(year) LIKE upper(?) AND
             upper(category) LIKE upper(?)",
             "%#{title}%", "%#{director}%", "%#{second_year}%", "%#{category}%")
    elsif second_year.blank?
      where("upper(title) LIKE upper(?) AND
            upper(director) LIKE upper(?) AND
            upper(year) LIKE upper(?) AND
            upper(category) LIKE upper(?)",
            "%#{title}%", "%#{director}%", "%#{first_year}%", "%#{category}%")
    else
      where("upper(title) LIKE upper(?) AND
             upper(director) LIKE upper(?) AND
             upper(year) >= upper(?) AND upper(year) <= upper(?) AND
             upper(category) LIKE upper(?)",
             "%#{title}%", "%#{director}%", "#{first_year}", "#{second_year}",
             "%#{category}%")
    end
  end

  def create_content(content_params)
    unless content_params[:file_path].nil?
      upload = content_params[:file_path]
      File.open(Rails.root.join('public', 'uploads', upload.original_filename), 'wb') do |file|
        file.write(upload.read)
      end
      content_params[:file_path] = upload.original_filename
    end
    save(content_params)
  end

  def update_content(content_params)
    unless content_params[:file_path].nil?
      upload = content_params[:file_path]
      File.open(Rails.root.join('public', 'uploads', upload.original_filename), 'wb') do |file|
        file.write(upload.read)
      end
      content_params[:file_path] = upload.original_filename
    end
    update(content_params)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_manager, only: %i[new create]
  before_action :set_content, only: %i[show edit update destroy]

  def index
    @contents = Content.includes(:user_content).all
    if search_params.empty?
      @contents = Content.includes(:user_content).all.order('year DESC')
    else
      @contents = Content.includes(:user_content)
                         .search(search_params[:title],
                                 search_params[:director],
                                 search_params[:first_year],
                                 search_params[:second_year],
                                 search_params[:category])
                         .order("year #{search_params[:order]}")
    end
  end

  def show
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.create_content(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update_content(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def content_params
    attrs = %i[title director year category file_path]
    params.require(:content).permit(attrs)
  end

  def search_params
    attrs = %w[title director first_year second_year category order]
    params.permit(attrs)
  end

  def authorize_manager
    redirect_back(fallback_location: root_path) unless current_user.is_manager
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <div class="field">
      <%= form.label :title, class: "label" %>
      <%= form.text_field :title, value: content.title, class: "input"%>
    </div>

    <div class="field">
      <%= form.label :director, class: "label" %>
      <%= form.text_field :director, value: content.director, class: "input" %>
    </div>

    <div class="field">
      <%= form.label :year, class: "label" %>
      <%= form.text_field :year, value: content.year, class: "input"%>
    </div>

    <div class="field">
      <%= form.label :category, class: "label" %>
      <%= form.text_field :category, value: content.category, class: "input"%>
    </div>

    <div class="field">
      <%= form.label :file_path, class: "label" %>
      <%= form.file_field :file_path, value: "public/uploads/#{content.file_path}", accept: 'image/png,image/jpg,image/jpeg'%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button"%>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Contents</h1>

<%= render 'partials/search_bar' %>
<%= render 'partials/contents_table', contents: @contents %>

<br>

<% if current_user.is_manager %>
  <%= link_to 'New Content', new_content_path %>
<% end %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show">
  <div class="attr">
    <ul>
      <li><b> Title </b> <%= @content.title %></li>
      <li><b> Director </b> <%= @content.director %></li>
      <li><b> Year </b> <%= @content.year %></li>
      <li><b> Category </b> <%= @content .category %></li>
    </ul>
  </div>
  <% if @content.file_path %>
    <div class="poster">
      <%= image_tag("/uploads/#{@content.file_path}") %>
    </div>
  <% end %>

  <% if current_user.is_manager %>
    <%= link_to 'Edit', edit_content_path(@content) %> |
  <% end %>
  <%= link_to 'Back', contents_path %>
</div>