config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/users/:id/watch_list', to: 'users_contents#index',
                               as: 'users_watch_list'

  get '/users/:id/change_role', to: 'users#change_role',
                                as: 'user_change_role'

  devise_for :users, skip: [:registrations]

  resources :users
  resources :contents

  get 'contents/:id/add_favorite', to: 'users_contents#add_favorite',
                                   as: 'add_favorite'
  get 'contents/:id/remove_favorite', to: 'users_contents#remove_favorite',
                                      as: 'remove_favorite'
  get 'contents/:id/add_rating', to: 'users_contents#add_rating',
                                 as: 'add_rating'
  get 'contents/:id/add_watch_list', to: 'users_contents#add_watch_list',
                                     as: 'add_watch_list'
  get 'contents/:id/remove_watch_list', to: 'users_contents#remove_watch_list',
                                        as: 'remove_watch_list'
end

app/views/partials/_contents_table.html.erb
<table class="table is-bordered is-hoverable">
  <thead>
    <tr>
      <th colspan="1"> <b> Title </b> </th>
      <th colspan="1"> <b> Director </b> </th>
      <th colspan="1"> <b> Year </b> </th>
      <th colspan="1"> <b> Category </b> </th>
  </thead>
  <tbody>
    <% contents.each do |content| %>
      <tr>
        <td><%= link_to content.title, content %></td>
        <td> <%= content.director %> </td>
        <td> <%= content.year %> </td>
        <td ><%= content .category %> </td> 
        <% if current_user.is_manager? %>
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <% if !content.user_content.first.nil? && content.user_content.first.user_id == current_user.id %>
            <td> <%= link_to 'Remove from watch list', remove_watch_list_path(content) %> </td>
          <% else %>
            <td> <%= link_to 'Add to watch list', add_watch_list_path(content) %> </td>
          <% end %>
          <% if !content.user_content.first.nil? && content.user_content.first.favorite %>
            <td> <%= link_to 'Remove from favorites', remove_favorite_path(content) %> </td>
          <% else %>
            <td> <%= link_to 'Add to favorites', add_favorite_path(content) %> </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_navbar.html.erb
<div class="navbar">
  <div class="wrapper">
    <% if user_signed_in? %>
      <div class="item"> <%= link_to('Dashboard', dashboard_path) %> </div>
      <div class="item"> <%= link_to('My Profile', user_path(current_user)) %> </div>
      <div class="item"> <%= link_to('Contents', contents_path)%> </div>
      <div class="item"> <%= link_to('Logout', destroy_user_session_path, method: :delete) %> </div>
    <% else %>
      <div class="item"> <%= link_to('Home Screen', root_path) %> </div>
      <div class="item"> <%= link_to('Register', new_user_path) %> </div>
      <div class="item"> <%= link_to('Login', new_user_session_path) %> </div>
    <% end %>
  </div>
</div>

app/views/partials/_search_bar.html.erb
<div class="search">
  <%= form_tag(request.original_url, :method => 'get') do %>
    <%= text_field_tag :title, params[:title], placeholder: "Search title", value: "", class: "input" %>
    <%= text_field_tag :director, params[:director], placeholder: "Search director", value: "", class: "input" %>
    <%= text_field_tag :first_year, params[:first_year], placeholder: "Inital year of range", value: "", class: "input" %>
    <%= text_field_tag :second_year, params[:second_year], placeholder: "Final year of range", value: "", class: "input" %>
    <%= text_field_tag :category, params[:category], placeholder: "Search category", value: "", class: "input" %>
    <%= radio_button_tag :order, "DESC", checked: true, class:"radio"%> Descending 
    <%= radio_button_tag :order, "ASC", checked:false, class:"radio" %> Ascending 
    <%= submit_tag "Search", :name => nil, class: "button" %>
<% end %>
</div>