config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/users/:id/watch_list', to: 'users_contents#index',
                               as: 'users_watch_list'

  get '/users/:id/change_role', to: 'users#change_role',
                                as: 'user_change_role'

  devise_for :users, skip: [:registrations]

  resources :users
  resources :contents

  get 'contents/:id/add_favorite', to: 'users_contents#add_favorite',
                                   as: 'add_favorite'
  get 'contents/:id/remove_favorite', to: 'users_contents#remove_favorite',
                                      as: 'remove_favorite'
  get 'contents/:id/add_rating', to: 'users_contents#add_rating',
                                 as: 'add_rating'
  get 'contents/:id/add_watch_list', to: 'users_contents#add_watch_list',
                                     as: 'add_watch_list'
  get 'contents/:id/remove_watch_list', to: 'users_contents#remove_watch_list',
                                        as: 'remove_watch_list'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_content, dependent: :destroy
  has_many :contents, through: :user_content, dependent: :destroy

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  validates :encrypted_password, presence: true
  validates :credit_card_number, presence: true
  validates :email, presence: true
  validates_confirmation_of :password

  def change_role
    new_role = is_manager ? false : true
    update_attribute(:is_manager, new_role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[new create]
  before_action :protect_profile, except: %i[new create]

  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.next_payment = Time.now

    sign_in(@user)

    if @user.save
      flash[:success] = 'User created successfully'
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
    @favorites = UserContent.includes(:content).where(user_id: current_user.id, favorite: true)
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PATCH /users/:id
  def update
    @user = User.find(params[:id])

    sign_in(@user)

    if @user.update(user_params)
      flash[:success] = 'User updated successfully'
      redirect_to dashboard_path
    else
      render 'edit'
    end
  end

  # DELETE /users/:id
  def destroy
    user = User.find(params[:id])

    if user.destroy
      flash[:success] = 'User deleted successfully'
    else
      flash[:danger] = 'User could not be deleted'
    end
    redirect_to dashboard_path
  end

  def change_role
    user = User.find(params[:id])
    user.change_role
    redirect_back(fallback_location: root_path)
  end

  private

  def user_params
    attrs = %i[email username password password_confirmation credit_card_number]
    params.require(:user).permit(attrs)
  end

  def protect_profile
    user = User.find_by(id: params[:id])
    redirect_back(fallback_location: root_path) unless !user.nil? && user.id == current_user.id
  end
end

app/views/users/_form_create.html.erb
<%= form_for(@user, html: { method: :post }) do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username,  autofocus: true, class: "input" %>
  </div> 

  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.email_field :email, autocomplete: "email", class: "input"%>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "new-password", class: "input" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "input" %>
  </div>

  <div class="field">
    <%= f.label :credit_card_number %>
    <%= f.text_field :credit_card_number, class: "input" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up", class: "button" %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for(@user, url: user_path(@user), method: :patch) do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username,  autofocus: true, class: "input" %>
  </div> 

  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.email_field :email, autocomplete: "email", class: "input"%>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: "new-password", class: "input" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "input" %>
  </div>

  <div class="field">
    <%= f.label :credit_card_number %>
    <%= f.text_field :credit_card_number, class: "input" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Information", class: "button" %>
  </div>
<% end %>

<%= link_to "Delete your account", @user, method: :delete, data: { confirm: "You sure?" } %>

app/views/users/edit.html.erb
<div> 
  <%= render 'form_edit' %>
</div>

app/views/users/form_password.html.erb
<div>
  <%= form_for(@user, :url => { :action => "update_password" } ) do |f| %>
    <div class="action_container">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div>
  <%= render 'form_create' %>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="attributes">
    <p> <b> Username: </b> <%= @user.username %> </p> 
    <p> <b> Email: </b> <%= @user.email %> </p> 
    <p> <b> Credit Card Number: </b> <%= @user.credit_card_number %> </p> 
    <p> <b> Next Payment: </b> <%= @user.next_payment %> </p> 
    <p> <b> Manager: </b> <%= @user.is_manager %> </p> 
  </div>

  <div class="favorites">
    <h2> <b> Favorite Content </b> </h2>
    <% @favorites.each do |favorite| %>
      <p><%= link_to favorite.content.title, favorite.content %></p>
    <% end %>
  </div>

  <div class="actions">
    <div> <%= link_to('Edit profile', edit_user_path(current_user)) %> </div>
    <div> <%= link_to('My Watch List', users_watch_list_path(current_user)) %> </div>
    <div> <%= link_to('Change role', user_change_role_path(current_user)) %> </div>
  </div>
</div>